name: cinema_world
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  go_router: ^14.3.0
  get_it: ^8.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4
  animate_do: ^3.3.4
  flutter_staggered_grid_view: ^0.7.0
  youtube_player_flutter: ^9.1.1
  card_swiper: ^3.0.1
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  searchfield: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  isar_generator: ^3.1.0+1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/splash/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: "assets/splash/background.png"
  image: "assets/splash/logo.png"
  branding: "assets/splash/branding.png"
  android_12:
    color: "#141418"
    image: "assets/splash/logo_android.png"
    branding: "assets/splash/branding_android.png"