import 'package:cinema_world/config/config.dart';
import 'package:cinema_world/features/movies/movies.dart';

class MovieMapper {
  static Movie movieDBToEntity(MovieMovieDB movieDB) => Movie(
        adult: movieDB.adult,
        backdropPath: movieDB.backdropPath != ''
            ? 'https://image.tmdb.org/t/p/w500/${movieDB.backdropPath}'
            : 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png',
        genreIds: movieDB.genreIds.map((e) => e.toString()).toList(),
        id: movieDB.id,
        originalLanguage: movieDB.originalLanguage,
        originalTitle: movieDB.originalTitle,
        overview: movieDB.overview,
        popularity: movieDB.popularity,
        posterPath: movieDB.posterPath != ''
            ? 'https://image.tmdb.org/t/p/w500/${movieDB.posterPath}'
            : 'https://movienewsletters.net/photos/000000H1.jpg',
        releaseDate:
            movieDB.releaseDate != null ? movieDB.releaseDate! : DateTime.now(),
        title: movieDB.title,
        video: movieDB.video,
        voteAverage: movieDB.voteAverage,
        voteCount: movieDB.voteCount,
        runtime: HumanFormats.hoursMinutes(movieDB.runtime),
      );

  static Movie movieDetailsToEntity(MovieDetails movie) => Movie(
        adult: movie.adult,
        backdropPath: movie.backdropPath != ''
            ? 'https://image.tmdb.org/t/p/w500/${movie.backdropPath}'
            : 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png',
        genreIds: movie.genres.map((e) => e.name).toList(),
        id: movie.id,
        originalLanguage: movie.originalLanguage,
        originalTitle: movie.originalTitle,
        overview: movie.overview,
        popularity: movie.popularity,
        posterPath: movie.posterPath != ''
            ? 'https://image.tmdb.org/t/p/w500/${movie.posterPath}'
            : 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png',
        releaseDate: movie.releaseDate,
        title: movie.title,
        video: movie.video,
        voteAverage: movie.voteAverage,
        voteCount: movie.voteCount,
        runtime: HumanFormats.hoursMinutes(movie.runtime),
      );

  static Movie moviesByActorToEntity(CastByActor movie) => Movie(
        adult: movie.adult,
        backdropPath: movie.backdropPath == '' || movie.backdropPath == null
            ? 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png'
            : 'https://image.tmdb.org/t/p/w500/${movie.backdropPath}',
        genreIds: movie.genreIds.map((e) => e.toString()).toList(),
        id: movie.id,
        originalLanguage: movie.originalLanguage,
        originalTitle: movie.originalTitle,
        overview: movie.overview,
        popularity: movie.popularity,
        posterPath: movie.posterPath == '' || movie.posterPath == null
            ? 'https://movienewsletters.net/photos/000000H1.jpg'
            : 'https://image.tmdb.org/t/p/w500/${movie.posterPath}',
        releaseDate: movie.releaseDate,
        title: movie.title,
        video: movie.video,
        voteAverage: movie.voteAverage,
        voteCount: movie.voteCount,
        runtime: HumanFormats.hoursMinutes(movie.runtime ?? 0),
      );

  static List<Providers> getProviders(List<Flatrate>? providers) {
    return providers
            ?.map((e) => Providers(
                  providerName: e.providerName,
                  logoPath: e.logoPath != ''
                      ? 'https://image.tmdb.org/t/p/w500/${e.logoPath}'
                      : 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Image-not-found.png',
                ))
            .toList() ??
        [];
  }

  static List<WatchProviders> watchProvidersToEntity(
      ProvidersResponse response) {
    final List<WatchProviders> watchProviders = [
      WatchProviders(
        isoCode: 'AF',
        nameCountry: Countries.isoToFlag('AF'),
        streaming: getProviders(response.results.ad.flatrate),
        rent: getProviders(response.results.ad.rent),
        buy: getProviders(response.results.ad.buy),
        ads: getProviders(response.results.ad.ads),
      ),
      WatchProviders(
        isoCode: 'AE',
        nameCountry: Countries.isoToFlag('AE'),
        streaming: getProviders(response.results.ae.flatrate),
        rent: getProviders(response.results.ae.rent),
        buy: getProviders(response.results.ae.buy),
        ads: getProviders(response.results.ae.ads),
      ),
      WatchProviders(
        isoCode: 'AG',
        nameCountry: Countries.isoToFlag('AG'),
        streaming: getProviders(response.results.ag.flatrate),
        rent: getProviders(response.results.ag.rent),
        buy: getProviders(response.results.ag.buy),
        ads: getProviders(response.results.ag.ads),
      ),
      WatchProviders(
        isoCode: 'AL',
        nameCountry: Countries.isoToFlag('AL'),
        streaming: getProviders(response.results.al.flatrate),
        rent: getProviders(response.results.al.rent),
        buy: getProviders(response.results.al.buy),
        ads: getProviders(response.results.al.ads),
      ),
      WatchProviders(
        isoCode: 'AO',
        nameCountry: Countries.isoToFlag('AO'),
        streaming: getProviders(response.results.ao.flatrate),
        rent: getProviders(response.results.ao.rent),
        buy: getProviders(response.results.ao.buy),
        ads: getProviders(response.results.ao.ads),
      ),
      WatchProviders(
        isoCode: 'AR',
        nameCountry: Countries.isoToFlag('AR'),
        streaming: getProviders(response.results.ar.flatrate),
        rent: getProviders(response.results.ar.rent),
        buy: getProviders(response.results.ar.buy),
        ads: getProviders(response.results.ar.ads),
      ),
      WatchProviders(
        isoCode: 'AT',
        nameCountry: Countries.isoToFlag('AT'),
        streaming: getProviders(response.results.at.flatrate),
        rent: getProviders(response.results.at.rent),
        buy: getProviders(response.results.at.buy),
        ads: getProviders(response.results.at.ads),
      ),
      WatchProviders(
        isoCode: 'AU',
        nameCountry: Countries.isoToFlag('AU'),
        streaming: getProviders(response.results.au.flatrate),
        rent: getProviders(response.results.au.rent),
        buy: getProviders(response.results.au.buy),
        ads: getProviders(response.results.au.ads),
      ),
      WatchProviders(
        isoCode: 'AZ',
        nameCountry: Countries.isoToFlag('AZ'),
        streaming: getProviders(response.results.az.flatrate),
        rent: getProviders(response.results.az.rent),
        buy: getProviders(response.results.az.buy),
        ads: getProviders(response.results.az.ads),
      ),
      WatchProviders(
        isoCode: 'BA',
        nameCountry: Countries.isoToFlag('BA'),
        streaming: getProviders(response.results.ba.flatrate),
        rent: getProviders(response.results.ba.rent),
        buy: getProviders(response.results.ba.buy),
        ads: getProviders(response.results.ba.ads),
      ),
      WatchProviders(
        isoCode: 'BB',
        nameCountry: Countries.isoToFlag('BB'),
        streaming: getProviders(response.results.bb.flatrate),
        rent: getProviders(response.results.bb.rent),
        buy: getProviders(response.results.bb.buy),
        ads: getProviders(response.results.bb.ads),
      ),
      WatchProviders(
        isoCode: 'BE',
        nameCountry: Countries.isoToFlag('BE'),
        streaming: getProviders(response.results.be.flatrate),
        rent: getProviders(response.results.be.rent),
        buy: getProviders(response.results.be.buy),
        ads: getProviders(response.results.be.ads),
      ),
      WatchProviders(
        isoCode: 'BF',
        nameCountry: Countries.isoToFlag('BF'),
        streaming: getProviders(response.results.bf.flatrate),
        rent: getProviders(response.results.bf.rent),
        buy: getProviders(response.results.bf.buy),
        ads: getProviders(response.results.bf.ads),
      ),
      WatchProviders(
        isoCode: 'BG',
        nameCountry: Countries.isoToFlag('BG'),
        streaming: getProviders(response.results.bg.flatrate),
        rent: getProviders(response.results.bg.rent),
        buy: getProviders(response.results.bg.buy),
        ads: getProviders(response.results.bg.ads),
      ),
      WatchProviders(
        isoCode: 'BH',
        nameCountry: Countries.isoToFlag('BH'),
        streaming: getProviders(response.results.bh.flatrate),
        rent: getProviders(response.results.bh.rent),
        buy: getProviders(response.results.bh.buy),
        ads: getProviders(response.results.bh.ads),
      ),
      WatchProviders(
        isoCode: 'BO',
        nameCountry: Countries.isoToFlag('BO'),
        streaming: getProviders(response.results.bo.flatrate),
        rent: getProviders(response.results.bo.rent),
        buy: getProviders(response.results.bo.buy),
        ads: getProviders(response.results.bo.ads),
      ),
      WatchProviders(
        isoCode: 'BR',
        nameCountry: Countries.isoToFlag('BR'),
        streaming: getProviders(response.results.br.flatrate),
        rent: getProviders(response.results.br.rent),
        buy: getProviders(response.results.br.buy),
        ads: getProviders(response.results.br.ads),
      ),
      WatchProviders(
        isoCode: 'BY',
        nameCountry: Countries.isoToFlag('BY'),
        streaming: getProviders(response.results.by.flatrate),
        rent: getProviders(response.results.by.rent),
        buy: getProviders(response.results.by.buy),
        ads: getProviders(response.results.by.ads),
      ),
      WatchProviders(
        isoCode: 'BZ',
        nameCountry: Countries.isoToFlag('BZ'),
        streaming: getProviders(response.results.bz.flatrate),
        rent: getProviders(response.results.bz.rent),
        buy: getProviders(response.results.bz.buy),
        ads: getProviders(response.results.bz.ads),
      ),
      WatchProviders(
        isoCode: 'CA',
        nameCountry: Countries.isoToFlag('CA'),
        streaming: getProviders(response.results.ca.flatrate),
        rent: getProviders(response.results.ca.rent),
        buy: getProviders(response.results.ca.buy),
        ads: getProviders(response.results.ca.ads),
      ),
      WatchProviders(
        isoCode: 'CH',
        nameCountry: Countries.isoToFlag('CH'),
        streaming: getProviders(response.results.ch.flatrate),
        rent: getProviders(response.results.ch.rent),
        buy: getProviders(response.results.ch.buy),
        ads: getProviders(response.results.ch.ads),
      ),
      WatchProviders(
        isoCode: 'CI',
        nameCountry: Countries.isoToFlag('CI'),
        streaming: getProviders(response.results.ci.flatrate),
        rent: getProviders(response.results.ci.rent),
        buy: getProviders(response.results.ci.buy),
        ads: getProviders(response.results.ci.ads),
      ),
      WatchProviders(
        isoCode: 'CL',
        nameCountry: Countries.isoToFlag('CL'),
        streaming: getProviders(response.results.cl.flatrate),
        rent: getProviders(response.results.cl.rent),
        buy: getProviders(response.results.cl.buy),
        ads: getProviders(response.results.cl.ads),
      ),
      WatchProviders(
        isoCode: 'CM',
        nameCountry: Countries.isoToFlag('CM'),
        streaming: getProviders(response.results.cm.flatrate),
        rent: getProviders(response.results.cm.rent),
        buy: getProviders(response.results.cm.buy),
        ads: getProviders(response.results.cm.ads),
      ),
      WatchProviders(
        isoCode: 'CO',
        nameCountry: Countries.isoToFlag('CO'),
        streaming: getProviders(response.results.co.flatrate),
        rent: getProviders(response.results.co.rent),
        buy: getProviders(response.results.co.buy),
        ads: getProviders(response.results.co.ads),
      ),
      WatchProviders(
        isoCode: 'CR',
        nameCountry: Countries.isoToFlag('CR'),
        streaming: getProviders(response.results.cr.flatrate),
        rent: getProviders(response.results.cr.rent),
        buy: getProviders(response.results.cr.buy),
        ads: getProviders(response.results.cr.ads),
      ),
      WatchProviders(
        isoCode: 'CV',
        nameCountry: Countries.isoToFlag('CV'),
        streaming: getProviders(response.results.cv.flatrate),
        rent: getProviders(response.results.cv.rent),
        buy: getProviders(response.results.cv.buy),
        ads: getProviders(response.results.cv.ads),
      ),
      WatchProviders(
        isoCode: 'CY',
        nameCountry: Countries.isoToFlag('CY'),
        streaming: getProviders(response.results.cy.flatrate),
        rent: getProviders(response.results.cy.rent),
        buy: getProviders(response.results.cy.buy),
        ads: getProviders(response.results.cy.ads),
      ),
      WatchProviders(
        isoCode: 'CZ',
        nameCountry: Countries.isoToFlag('CZ'),
        streaming: getProviders(response.results.cz.flatrate),
        rent: getProviders(response.results.cz.rent),
        buy: getProviders(response.results.cz.buy),
        ads: getProviders(response.results.cz.ads),
      ),
      WatchProviders(
        isoCode: 'DE',
        nameCountry: Countries.isoToFlag('DE'),
        streaming: getProviders(response.results.de.flatrate),
        rent: getProviders(response.results.de.rent),
        buy: getProviders(response.results.de.buy),
        ads: getProviders(response.results.de.ads),
      ),
      WatchProviders(
        isoCode: 'DK',
        nameCountry: Countries.isoToFlag('DK'),
        streaming: getProviders(response.results.dk.flatrate),
        rent: getProviders(response.results.dk.rent),
        buy: getProviders(response.results.dk.buy),
        ads: getProviders(response.results.dk.ads),
      ),
      WatchProviders(
        isoCode: 'DO',
        nameCountry: Countries.isoToFlag('DO'),
        streaming: getProviders(response.results.resultsDo.flatrate),
        rent: getProviders(response.results.resultsDo.rent),
        buy: getProviders(response.results.resultsDo.buy),
        ads: getProviders(response.results.resultsDo.ads),
      ),
      WatchProviders(
        isoCode: 'DZ',
        nameCountry: Countries.isoToFlag('DZ'),
        streaming: getProviders(response.results.dz.flatrate),
        rent: getProviders(response.results.dz.rent),
        buy: getProviders(response.results.dz.buy),
        ads: getProviders(response.results.dz.ads),
      ),
      WatchProviders(
        isoCode: 'EC',
        nameCountry: Countries.isoToFlag('EC'),
        streaming: getProviders(response.results.ec.flatrate),
        rent: getProviders(response.results.ec.rent),
        buy: getProviders(response.results.ec.buy),
        ads: getProviders(response.results.ec.ads),
      ),
      WatchProviders(
        isoCode: 'EE',
        nameCountry: Countries.isoToFlag('EE'),
        streaming: getProviders(response.results.ee.flatrate),
        rent: getProviders(response.results.ee.rent),
        buy: getProviders(response.results.ee.buy),
        ads: getProviders(response.results.ee.ads),
      ),
      WatchProviders(
        isoCode: 'EG',
        nameCountry: Countries.isoToFlag('EG'),
        streaming: getProviders(response.results.eg.flatrate),
        rent: getProviders(response.results.eg.rent),
        buy: getProviders(response.results.eg.buy),
        ads: getProviders(response.results.eg.ads),
      ),
      WatchProviders(
        isoCode: 'ES',
        nameCountry: Countries.isoToFlag('ES'),
        streaming: getProviders(response.results.es.flatrate),
        rent: getProviders(response.results.es.rent),
        buy: getProviders(response.results.es.buy),
        ads: getProviders(response.results.es.ads),
      ),
      WatchProviders(
        isoCode: 'FI',
        nameCountry: Countries.isoToFlag('FI'),
        streaming: getProviders(response.results.fi.flatrate),
        rent: getProviders(response.results.fi.rent),
        buy: getProviders(response.results.fi.buy),
        ads: getProviders(response.results.fi.ads),
      ),
      WatchProviders(
        isoCode: 'FJ',
        nameCountry: Countries.isoToFlag('FJ'),
        streaming: getProviders(response.results.fj.flatrate),
        rent: getProviders(response.results.fj.rent),
        buy: getProviders(response.results.fj.buy),
        ads: getProviders(response.results.fj.ads),
      ),
      WatchProviders(
        isoCode: 'FR',
        nameCountry: Countries.isoToFlag('FR'),
        streaming: getProviders(response.results.fr.flatrate),
        rent: getProviders(response.results.fr.rent),
        buy: getProviders(response.results.fr.buy),
        ads: getProviders(response.results.fr.ads),
      ),
      WatchProviders(
        isoCode: 'GB',
        nameCountry: Countries.isoToFlag('GB'),
        streaming: getProviders(response.results.gb.flatrate),
        rent: getProviders(response.results.gb.rent),
        buy: getProviders(response.results.gb.buy),
        ads: getProviders(response.results.gb.ads),
      ),
      WatchProviders(
        isoCode: 'GF',
        nameCountry: Countries.isoToFlag('GF'),
        streaming: getProviders(response.results.gf.flatrate),
        rent: getProviders(response.results.gf.rent),
        buy: getProviders(response.results.gf.buy),
        ads: getProviders(response.results.gf.ads),
      ),
      WatchProviders(
        isoCode: 'GG',
        nameCountry: Countries.isoToFlag('GG'),
        streaming: getProviders(response.results.gg.flatrate),
        rent: getProviders(response.results.gg.rent),
        buy: getProviders(response.results.gg.buy),
        ads: getProviders(response.results.gg.ads),
      ),
      WatchProviders(
        isoCode: 'GH',
        nameCountry: Countries.isoToFlag('GH'),
        streaming: getProviders(response.results.gh.flatrate),
        rent: getProviders(response.results.gh.rent),
        buy: getProviders(response.results.gh.buy),
        ads: getProviders(response.results.gh.ads),
      ),
      WatchProviders(
        isoCode: 'GI',
        nameCountry: Countries.isoToFlag('GI'),
        streaming: getProviders(response.results.gi.flatrate),
        rent: getProviders(response.results.gi.rent),
        buy: getProviders(response.results.gi.buy),
        ads: getProviders(response.results.gi.ads),
      ),
      WatchProviders(
        isoCode: 'GQ',
        nameCountry: Countries.isoToFlag('GQ'),
        streaming: getProviders(response.results.gq.flatrate),
        rent: getProviders(response.results.gq.rent),
        buy: getProviders(response.results.gq.buy),
        ads: getProviders(response.results.gq.ads),
      ),
      WatchProviders(
        isoCode: 'GR',
        nameCountry: Countries.isoToFlag('GR'),
        streaming: getProviders(response.results.gr.flatrate),
        rent: getProviders(response.results.gr.rent),
        buy: getProviders(response.results.gr.buy),
        ads: getProviders(response.results.gr.ads),
      ),
      WatchProviders(
        isoCode: 'GT',
        nameCountry: Countries.isoToFlag('GT'),
        streaming: getProviders(response.results.gt.flatrate),
        rent: getProviders(response.results.gt.rent),
        buy: getProviders(response.results.gt.buy),
        ads: getProviders(response.results.gt.ads),
      ),
      WatchProviders(
        isoCode: 'HK',
        nameCountry: Countries.isoToFlag('HK'),
        streaming: getProviders(response.results.hk.flatrate),
        rent: getProviders(response.results.hk.rent),
        buy: getProviders(response.results.hk.buy),
        ads: getProviders(response.results.hk.ads),
      ),
      WatchProviders(
        isoCode: 'HN',
        nameCountry: Countries.isoToFlag('HN'),
        streaming: getProviders(response.results.hn.flatrate),
        rent: getProviders(response.results.hn.rent),
        buy: getProviders(response.results.hn.buy),
        ads: getProviders(response.results.hn.ads),
      ),
      WatchProviders(
        isoCode: 'HR',
        nameCountry: Countries.isoToFlag('HR'),
        streaming: getProviders(response.results.hr.flatrate),
        rent: getProviders(response.results.hr.rent),
        buy: getProviders(response.results.hr.buy),
        ads: getProviders(response.results.hr.ads),
      ),
      WatchProviders(
        isoCode: 'HU',
        nameCountry: Countries.isoToFlag('HU'),
        streaming: getProviders(response.results.hu.flatrate),
        rent: getProviders(response.results.hu.rent),
        buy: getProviders(response.results.hu.buy),
        ads: getProviders(response.results.hu.ads),
      ),
      WatchProviders(
        isoCode: 'ID',
        nameCountry: Countries.isoToFlag('ID'),
        streaming: getProviders(response.results.id.flatrate),
        rent: getProviders(response.results.id.rent),
        buy: getProviders(response.results.id.buy),
        ads: getProviders(response.results.id.ads),
      ),
      WatchProviders(
        isoCode: 'IE',
        nameCountry: Countries.isoToFlag('IE'),
        streaming: getProviders(response.results.ie.flatrate),
        rent: getProviders(response.results.ie.rent),
        buy: getProviders(response.results.ie.buy),
        ads: getProviders(response.results.ie.ads),
      ),
      WatchProviders(
        isoCode: 'IL',
        nameCountry: Countries.isoToFlag('IL'),
        streaming: getProviders(response.results.il.flatrate),
        rent: getProviders(response.results.il.rent),
        buy: getProviders(response.results.il.buy),
        ads: getProviders(response.results.il.ads),
      ),
      WatchProviders(
        isoCode: 'IN',
        nameCountry: Countries.isoToFlag('IN'),
        streaming: getProviders(response.results.resultsIn.flatrate),
        rent: getProviders(response.results.resultsIn.rent),
        buy: getProviders(response.results.resultsIn.buy),
        ads: getProviders(response.results.resultsIn.ads),
      ),
      WatchProviders(
        isoCode: 'IQ',
        nameCountry: Countries.isoToFlag('IQ'),
        streaming: getProviders(response.results.iq.flatrate),
        rent: getProviders(response.results.iq.rent),
        buy: getProviders(response.results.iq.buy),
        ads: getProviders(response.results.iq.ads),
      ),
      WatchProviders(
        isoCode: 'IS',
        nameCountry: Countries.isoToFlag('IS'),
        streaming: getProviders(response.results.resultsIs.flatrate),
        rent: getProviders(response.results.resultsIs.rent),
        buy: getProviders(response.results.resultsIs.buy),
        ads: getProviders(response.results.resultsIs.ads),
      ),
      WatchProviders(
        isoCode: 'IT',
        nameCountry: Countries.isoToFlag('IT'),
        streaming: getProviders(response.results.it.flatrate),
        rent: getProviders(response.results.it.rent),
        buy: getProviders(response.results.it.buy),
        ads: getProviders(response.results.it.ads),
      ),
      WatchProviders(
        isoCode: 'JM',
        nameCountry: Countries.isoToFlag('JM'),
        streaming: getProviders(response.results.jm.flatrate),
        rent: getProviders(response.results.jm.rent),
        buy: getProviders(response.results.jm.buy),
        ads: getProviders(response.results.jm.ads),
      ),
      WatchProviders(
        isoCode: 'JO',
        nameCountry: Countries.isoToFlag('JO'),
        streaming: getProviders(response.results.jo.flatrate),
        rent: getProviders(response.results.jo.rent),
        buy: getProviders(response.results.jo.buy),
        ads: getProviders(response.results.jo.ads),
      ),
      WatchProviders(
        isoCode: 'JP',
        nameCountry: Countries.isoToFlag('JP'),
        streaming: getProviders(response.results.jp.flatrate),
        rent: getProviders(response.results.jp.rent),
        buy: getProviders(response.results.jp.buy),
        ads: getProviders(response.results.jp.ads),
      ),
      WatchProviders(
        isoCode: 'KE',
        nameCountry: Countries.isoToFlag('KE'),
        streaming: getProviders(response.results.ke.flatrate),
        rent: getProviders(response.results.ke.rent),
        buy: getProviders(response.results.ke.buy),
        ads: getProviders(response.results.ke.ads),
      ),
      WatchProviders(
        isoCode: 'KR',
        nameCountry: Countries.isoToFlag('KR'),
        streaming: getProviders(response.results.kr.flatrate),
        rent: getProviders(response.results.kr.rent),
        buy: getProviders(response.results.kr.buy),
        ads: getProviders(response.results.kr.ads),
      ),
      WatchProviders(
        isoCode: 'KW',
        nameCountry: Countries.isoToFlag('KW'),
        streaming: getProviders(response.results.kw.flatrate),
        rent: getProviders(response.results.kw.rent),
        buy: getProviders(response.results.kw.buy),
        ads: getProviders(response.results.kw.ads),
      ),
      WatchProviders(
        isoCode: 'LB',
        nameCountry: Countries.isoToFlag('LB'),
        streaming: getProviders(response.results.lb.flatrate),
        rent: getProviders(response.results.lb.rent),
        buy: getProviders(response.results.lb.buy),
        ads: getProviders(response.results.lb.ads),
      ),
      WatchProviders(
        isoCode: 'LC',
        nameCountry: Countries.isoToFlag('LC'),
        streaming: getProviders(response.results.lc.flatrate),
        rent: getProviders(response.results.lc.rent),
        buy: getProviders(response.results.lc.buy),
        ads: getProviders(response.results.lc.ads),
      ),
      WatchProviders(
        isoCode: 'LI',
        nameCountry: Countries.isoToFlag('LI'),
        streaming: getProviders(response.results.li.flatrate),
        rent: getProviders(response.results.li.rent),
        buy: getProviders(response.results.li.buy),
        ads: getProviders(response.results.li.ads),
      ),
      WatchProviders(
        isoCode: 'LT',
        nameCountry: Countries.isoToFlag('LT'),
        streaming: getProviders(response.results.lt.flatrate),
        rent: getProviders(response.results.lt.rent),
        buy: getProviders(response.results.lt.buy),
        ads: getProviders(response.results.lt.ads),
      ),
      WatchProviders(
        isoCode: 'LU',
        nameCountry: Countries.isoToFlag('LU'),
        streaming: getProviders(response.results.lu.flatrate),
        rent: getProviders(response.results.lu.rent),
        buy: getProviders(response.results.lu.buy),
        ads: getProviders(response.results.lu.ads),
      ),
      WatchProviders(
        isoCode: 'LV',
        nameCountry: Countries.isoToFlag('LV'),
        streaming: getProviders(response.results.lv.flatrate),
        rent: getProviders(response.results.lv.rent),
        buy: getProviders(response.results.lv.buy),
        ads: getProviders(response.results.lv.ads),
      ),
      WatchProviders(
        isoCode: 'LY',
        nameCountry: Countries.isoToFlag('LY'),
        streaming: getProviders(response.results.ly.flatrate),
        rent: getProviders(response.results.ly.rent),
        buy: getProviders(response.results.ly.buy),
        ads: getProviders(response.results.ly.ads),
      ),
      WatchProviders(
        isoCode: 'MA',
        nameCountry: Countries.isoToFlag('MA'),
        streaming: getProviders(response.results.ma.flatrate),
        rent: getProviders(response.results.ma.rent),
        buy: getProviders(response.results.ma.buy),
        ads: getProviders(response.results.ma.ads),
      ),
      WatchProviders(
        isoCode: 'MC',
        nameCountry: Countries.isoToFlag('MC'),
        streaming: getProviders(response.results.mc.flatrate),
        rent: getProviders(response.results.mc.rent),
        buy: getProviders(response.results.mc.buy),
        ads: getProviders(response.results.mc.ads),
      ),
      WatchProviders(
        isoCode: 'MD',
        nameCountry: Countries.isoToFlag('MD'),
        streaming: getProviders(response.results.md.flatrate),
        rent: getProviders(response.results.md.rent),
        buy: getProviders(response.results.md.buy),
        ads: getProviders(response.results.md.ads),
      ),
      WatchProviders(
        isoCode: 'ME',
        nameCountry: Countries.isoToFlag('ME'),
        streaming: getProviders(response.results.me.flatrate),
        rent: getProviders(response.results.me.rent),
        buy: getProviders(response.results.me.buy),
        ads: getProviders(response.results.me.ads),
      ),
      WatchProviders(
        isoCode: 'MG',
        nameCountry: Countries.isoToFlag('MG'),
        streaming: getProviders(response.results.mg.flatrate),
        rent: getProviders(response.results.mg.rent),
        buy: getProviders(response.results.mg.buy),
        ads: getProviders(response.results.mg.ads),
      ),
      WatchProviders(
        isoCode: 'MK',
        nameCountry: Countries.isoToFlag('MK'),
        streaming: getProviders(response.results.mk.flatrate),
        rent: getProviders(response.results.mk.rent),
        buy: getProviders(response.results.mk.buy),
        ads: getProviders(response.results.mk.ads),
      ),
      WatchProviders(
        isoCode: 'ML',
        nameCountry: Countries.isoToFlag('ML'),
        streaming: getProviders(response.results.ml.flatrate),
        rent: getProviders(response.results.ml.rent),
        buy: getProviders(response.results.ml.buy),
        ads: getProviders(response.results.ml.ads),
      ),
      WatchProviders(
        isoCode: 'MT',
        nameCountry: Countries.isoToFlag('MT'),
        streaming: getProviders(response.results.mt.flatrate),
        rent: getProviders(response.results.mt.rent),
        buy: getProviders(response.results.mt.buy),
        ads: getProviders(response.results.mt.ads),
      ),
      WatchProviders(
        isoCode: 'MU',
        nameCountry: Countries.isoToFlag('MU'),
        streaming: getProviders(response.results.mu.flatrate),
        rent: getProviders(response.results.mu.rent),
        buy: getProviders(response.results.mu.buy),
        ads: getProviders(response.results.mu.ads),
      ),
      WatchProviders(
        isoCode: 'MX',
        nameCountry: Countries.isoToFlag('MX'),
        streaming: getProviders(response.results.mx.flatrate),
        rent: getProviders(response.results.mx.rent),
        buy: getProviders(response.results.mx.buy),
        ads: getProviders(response.results.mx.ads),
      ),
      WatchProviders(
        isoCode: 'MY',
        nameCountry: Countries.isoToFlag('MY'),
        streaming: getProviders(response.results.my.flatrate),
        rent: getProviders(response.results.my.rent),
        buy: getProviders(response.results.my.buy),
        ads: getProviders(response.results.my.ads),
      ),
      WatchProviders(
        isoCode: 'MZ',
        nameCountry: Countries.isoToFlag('MZ'),
        streaming: getProviders(response.results.mz.flatrate),
        rent: getProviders(response.results.mz.rent),
        buy: getProviders(response.results.mz.buy),
        ads: getProviders(response.results.mz.ads),
      ),
      WatchProviders(
        isoCode: 'NE',
        nameCountry: Countries.isoToFlag('NE'),
        streaming: getProviders(response.results.ne.flatrate),
        rent: getProviders(response.results.ne.rent),
        buy: getProviders(response.results.ne.buy),
        ads: getProviders(response.results.ne.ads),
      ),
      WatchProviders(
        isoCode: 'NG',
        nameCountry: Countries.isoToFlag('NG'),
        streaming: getProviders(response.results.ng.flatrate),
        rent: getProviders(response.results.ng.rent),
        buy: getProviders(response.results.ng.buy),
        ads: getProviders(response.results.ng.ads),
      ),
      WatchProviders(
        isoCode: 'NI',
        nameCountry: Countries.isoToFlag('NI'),
        streaming: getProviders(response.results.ni.flatrate),
        rent: getProviders(response.results.ni.rent),
        buy: getProviders(response.results.ni.buy),
        ads: getProviders(response.results.ni.ads),
      ),
      WatchProviders(
        isoCode: 'NL',
        nameCountry: Countries.isoToFlag('NL'),
        streaming: getProviders(response.results.nl.flatrate),
        rent: getProviders(response.results.nl.rent),
        buy: getProviders(response.results.nl.buy),
        ads: getProviders(response.results.nl.ads),
      ),
      WatchProviders(
        isoCode: 'NO',
        nameCountry: Countries.isoToFlag('NO'),
        streaming: getProviders(response.results.no.flatrate),
        rent: getProviders(response.results.no.rent),
        buy: getProviders(response.results.no.buy),
        ads: getProviders(response.results.no.ads),
      ),
      WatchProviders(
        isoCode: 'NZ',
        nameCountry: Countries.isoToFlag('NZ'),
        streaming: getProviders(response.results.nz.flatrate),
        rent: getProviders(response.results.nz.rent),
        buy: getProviders(response.results.nz.buy),
        ads: getProviders(response.results.nz.ads),
      ),
      WatchProviders(
        isoCode: 'OM',
        nameCountry: Countries.isoToFlag('OM'),
        streaming: getProviders(response.results.om.flatrate),
        rent: getProviders(response.results.om.rent),
        buy: getProviders(response.results.om.buy),
        ads: getProviders(response.results.om.ads),
      ),
      WatchProviders(
        isoCode: 'PA',
        nameCountry: Countries.isoToFlag('PA'),
        streaming: getProviders(response.results.pa.flatrate),
        rent: getProviders(response.results.pa.rent),
        buy: getProviders(response.results.pa.buy),
        ads: getProviders(response.results.pa.ads),
      ),
      WatchProviders(
        isoCode: 'PE',
        nameCountry: Countries.isoToFlag('PE'),
        streaming: getProviders(response.results.pe.flatrate),
        rent: getProviders(response.results.pe.rent),
        buy: getProviders(response.results.pe.buy),
        ads: getProviders(response.results.pe.ads),
      ),
      WatchProviders(
        isoCode: 'PF',
        nameCountry: Countries.isoToFlag('PF'),
        streaming: getProviders(response.results.pf.flatrate),
        rent: getProviders(response.results.pf.rent),
        buy: getProviders(response.results.pf.buy),
        ads: getProviders(response.results.pf.ads),
      ),
      WatchProviders(
        isoCode: 'PG',
        nameCountry: Countries.isoToFlag('PG'),
        streaming: getProviders(response.results.pg.flatrate),
        rent: getProviders(response.results.pg.rent),
        buy: getProviders(response.results.pg.buy),
        ads: getProviders(response.results.pg.ads),
      ),
      WatchProviders(
        isoCode: 'PH',
        nameCountry: Countries.isoToFlag('PH'),
        streaming: getProviders(response.results.ph.flatrate),
        rent: getProviders(response.results.ph.rent),
        buy: getProviders(response.results.ph.buy),
        ads: getProviders(response.results.ph.ads),
      ),
      WatchProviders(
        isoCode: 'PK',
        nameCountry: Countries.isoToFlag('PK'),
        streaming: getProviders(response.results.pk.flatrate),
        rent: getProviders(response.results.pk.rent),
        buy: getProviders(response.results.pk.buy),
        ads: getProviders(response.results.pk.ads),
      ),
      WatchProviders(
        isoCode: 'PL',
        nameCountry: Countries.isoToFlag('PL'),
        streaming: getProviders(response.results.pl.flatrate),
        rent: getProviders(response.results.pl.rent),
        buy: getProviders(response.results.pl.buy),
        ads: getProviders(response.results.pl.ads),
      ),
      WatchProviders(
        isoCode: 'PS',
        nameCountry: Countries.isoToFlag('PS'),
        streaming: getProviders(response.results.ps.flatrate),
        rent: getProviders(response.results.ps.rent),
        buy: getProviders(response.results.ps.buy),
        ads: getProviders(response.results.ps.ads),
      ),
      WatchProviders(
        isoCode: 'PT',
        nameCountry: Countries.isoToFlag('PT'),
        streaming: getProviders(response.results.pt.flatrate),
        rent: getProviders(response.results.pt.rent),
        buy: getProviders(response.results.pt.buy),
        ads: getProviders(response.results.pt.ads),
      ),
      WatchProviders(
        isoCode: 'PY',
        nameCountry: Countries.isoToFlag('PY'),
        streaming: getProviders(response.results.py.flatrate),
        rent: getProviders(response.results.py.rent),
        buy: getProviders(response.results.py.buy),
        ads: getProviders(response.results.py.ads),
      ),
      WatchProviders(
        isoCode: 'QA',
        nameCountry: Countries.isoToFlag('QA'),
        streaming: getProviders(response.results.qa.flatrate),
        rent: getProviders(response.results.qa.rent),
        buy: getProviders(response.results.qa.buy),
        ads: getProviders(response.results.qa.ads),
      ),
      WatchProviders(
        isoCode: 'RO',
        nameCountry: Countries.isoToFlag('RO'),
        streaming: getProviders(response.results.ro.flatrate),
        rent: getProviders(response.results.ro.rent),
        buy: getProviders(response.results.ro.buy),
        ads: getProviders(response.results.ro.ads),
      ),
      WatchProviders(
        isoCode: 'RS',
        nameCountry: Countries.isoToFlag('RS'),
        streaming: getProviders(response.results.rs.flatrate),
        rent: getProviders(response.results.rs.rent),
        buy: getProviders(response.results.rs.buy),
        ads: getProviders(response.results.rs.ads),
      ),
      WatchProviders(
        isoCode: 'RU',
        nameCountry: Countries.isoToFlag('RU'),
        streaming: getProviders(response.results.ru.flatrate),
        rent: getProviders(response.results.ru.rent),
        buy: getProviders(response.results.ru.buy),
        ads: getProviders(response.results.ru.ads),
      ),
      WatchProviders(
        isoCode: 'SA',
        nameCountry: Countries.isoToFlag('SA'),
        streaming: getProviders(response.results.sa.flatrate),
        rent: getProviders(response.results.sa.rent),
        buy: getProviders(response.results.sa.buy),
        ads: getProviders(response.results.sa.ads),
      ),
      WatchProviders(
        isoCode: 'SC',
        nameCountry: Countries.isoToFlag('SC'),
        streaming: getProviders(response.results.sc.flatrate),
        rent: getProviders(response.results.sc.rent),
        buy: getProviders(response.results.sc.buy),
        ads: getProviders(response.results.sc.ads),
      ),
      WatchProviders(
        isoCode: 'SE',
        nameCountry: Countries.isoToFlag('SE'),
        streaming: getProviders(response.results.se.flatrate),
        rent: getProviders(response.results.se.rent),
        buy: getProviders(response.results.se.buy),
        ads: getProviders(response.results.se.ads),
      ),
      WatchProviders(
        isoCode: 'SG',
        nameCountry: Countries.isoToFlag('SG'),
        streaming: getProviders(response.results.sg.flatrate),
        rent: getProviders(response.results.sg.rent),
        buy: getProviders(response.results.sg.buy),
        ads: getProviders(response.results.sg.ads),
      ),
      WatchProviders(
        isoCode: 'SI',
        nameCountry: Countries.isoToFlag('SI'),
        streaming: getProviders(response.results.si.flatrate),
        rent: getProviders(response.results.si.rent),
        buy: getProviders(response.results.si.buy),
        ads: getProviders(response.results.si.ads),
      ),
      WatchProviders(
        isoCode: 'SK',
        nameCountry: Countries.isoToFlag('SK'),
        streaming: getProviders(response.results.sk.flatrate),
        rent: getProviders(response.results.sk.rent),
        buy: getProviders(response.results.sk.buy),
        ads: getProviders(response.results.sk.ads),
      ),
      WatchProviders(
        isoCode: 'SM',
        nameCountry: Countries.isoToFlag('SM'),
        streaming: getProviders(response.results.sm.flatrate),
        rent: getProviders(response.results.sm.rent),
        buy: getProviders(response.results.sm.buy),
        ads: getProviders(response.results.sm.ads),
      ),
      WatchProviders(
        isoCode: 'SN',
        nameCountry: Countries.isoToFlag('SN'),
        streaming: getProviders(response.results.sn.flatrate),
        rent: getProviders(response.results.sn.rent),
        buy: getProviders(response.results.sn.buy),
        ads: getProviders(response.results.sn.ads),
      ),
      WatchProviders(
        isoCode: 'SV',
        nameCountry: Countries.isoToFlag('SV'),
        streaming: getProviders(response.results.sv.flatrate),
        rent: getProviders(response.results.sv.rent),
        buy: getProviders(response.results.sv.buy),
        ads: getProviders(response.results.sv.ads),
      ),
      WatchProviders(
        isoCode: 'TC',
        nameCountry: Countries.isoToFlag('TC'),
        streaming: getProviders(response.results.tc.flatrate),
        rent: getProviders(response.results.tc.rent),
        buy: getProviders(response.results.tc.buy),
        ads: getProviders(response.results.tc.ads),
      ),
      WatchProviders(
        isoCode: 'TH',
        nameCountry: Countries.isoToFlag('TH'),
        streaming: getProviders(response.results.th.flatrate),
        rent: getProviders(response.results.th.rent),
        buy: getProviders(response.results.th.buy),
        ads: getProviders(response.results.th.ads),
      ),
      WatchProviders(
        isoCode: 'TN',
        nameCountry: Countries.isoToFlag('TN'),
        streaming: getProviders(response.results.tn.flatrate),
        rent: getProviders(response.results.tn.rent),
        buy: getProviders(response.results.tn.buy),
        ads: getProviders(response.results.tn.ads),
      ),
      WatchProviders(
        isoCode: 'TR',
        nameCountry: Countries.isoToFlag('TR'),
        streaming: getProviders(response.results.tr.flatrate),
        rent: getProviders(response.results.tr.rent),
        buy: getProviders(response.results.tr.buy),
        ads: getProviders(response.results.tr.ads),
      ),
      WatchProviders(
        isoCode: 'TT',
        nameCountry: Countries.isoToFlag('TT'),
        streaming: getProviders(response.results.tt.flatrate),
        rent: getProviders(response.results.tt.rent),
        buy: getProviders(response.results.tt.buy),
        ads: getProviders(response.results.tt.ads),
      ),
      WatchProviders(
        isoCode: 'TW',
        nameCountry: Countries.isoToFlag('TW'),
        streaming: getProviders(response.results.tw.flatrate),
        rent: getProviders(response.results.tw.rent),
        buy: getProviders(response.results.tw.buy),
        ads: getProviders(response.results.tw.ads),
      ),
      WatchProviders(
        isoCode: 'TZ',
        nameCountry: Countries.isoToFlag('TZ'),
        streaming: getProviders(response.results.tz.flatrate),
        rent: getProviders(response.results.tz.rent),
        buy: getProviders(response.results.tz.buy),
        ads: getProviders(response.results.tz.ads),
      ),
      WatchProviders(
        isoCode: 'UA',
        nameCountry: Countries.isoToFlag('UA'),
        streaming: getProviders(response.results.ua.flatrate),
        rent: getProviders(response.results.ua.rent),
        buy: getProviders(response.results.ua.buy),
        ads: getProviders(response.results.ua.ads),
      ),
      WatchProviders(
        isoCode: 'UG',
        nameCountry: Countries.isoToFlag('UG'),
        streaming: getProviders(response.results.ug.flatrate),
        rent: getProviders(response.results.ug.rent),
        buy: getProviders(response.results.ug.buy),
        ads: getProviders(response.results.ug.ads),
      ),
      WatchProviders(
        isoCode: 'US',
        nameCountry: Countries.isoToFlag('US'),
        streaming: getProviders(response.results.us.flatrate),
        rent: getProviders(response.results.us.rent),
        buy: getProviders(response.results.us.buy),
        ads: getProviders(response.results.us.ads),
      ),
      WatchProviders(
        isoCode: 'UY',
        nameCountry: Countries.isoToFlag('UY'),
        streaming: getProviders(response.results.uy.flatrate),
        rent: getProviders(response.results.uy.rent),
        buy: getProviders(response.results.uy.buy),
        ads: getProviders(response.results.uy.ads),
      ),
      WatchProviders(
        isoCode: 'VE',
        nameCountry: Countries.isoToFlag('VE'),
        streaming: getProviders(response.results.ve.flatrate),
        rent: getProviders(response.results.ve.rent),
        buy: getProviders(response.results.ve.buy),
        ads: getProviders(response.results.ve.ads),
      ),
      WatchProviders(
        isoCode: 'ZA',
        nameCountry: Countries.isoToFlag('ZA'),
        streaming: getProviders(response.results.za.flatrate),
        rent: getProviders(response.results.za.rent),
        buy: getProviders(response.results.za.buy),
        ads: getProviders(response.results.za.ads),
      ),
      WatchProviders(
        isoCode: 'ZW',
        nameCountry: Countries.isoToFlag('ZW'),
        streaming: getProviders(response.results.zw.flatrate),
        rent: getProviders(response.results.zw.rent),
        buy: getProviders(response.results.zw.buy),
        ads: getProviders(response.results.zw.ads),
      ),
      WatchProviders(
        isoCode: 'BT',
        nameCountry: Countries.isoToFlag('BT'),
        streaming: getProviders(response.results.bt.flatrate),
        rent: getProviders(response.results.bt.rent),
        buy: getProviders(response.results.bt.buy),
        ads: getProviders(response.results.bt.ads),
      ),
      WatchProviders(
        isoCode: 'CF',
        nameCountry: Countries.isoToFlag('CF'),
        streaming: getProviders(response.results.cf.flatrate),
        rent: getProviders(response.results.cf.rent),
        buy: getProviders(response.results.cf.buy),
        ads: getProviders(response.results.cf.ads),
      ),
      WatchProviders(
        isoCode: 'CD',
        nameCountry: Countries.isoToFlag('CD'),
        streaming: getProviders(response.results.cd.flatrate),
        rent: getProviders(response.results.cd.rent),
        buy: getProviders(response.results.cd.buy),
        ads: getProviders(response.results.cd.ads),
      ),
      WatchProviders(
        isoCode: 'SZ',
        nameCountry: Countries.isoToFlag('SZ'),
        streaming: getProviders(response.results.sz.flatrate),
        rent: getProviders(response.results.sz.rent),
        buy: getProviders(response.results.sz.buy),
        ads: getProviders(response.results.sz.ads),
      ),
      WatchProviders(
        isoCode: 'IR',
        nameCountry: Countries.isoToFlag('IR'),
        streaming: getProviders(response.results.ir.flatrate),
        rent: getProviders(response.results.ir.rent),
        buy: getProviders(response.results.ir.buy),
        ads: getProviders(response.results.ir.ads),
      ),
      WatchProviders(
        isoCode: 'KZ',
        nameCountry: Countries.isoToFlag('KZ'),
        streaming: getProviders(response.results.kz.flatrate),
        rent: getProviders(response.results.kz.rent),
        buy: getProviders(response.results.kz.buy),
        ads: getProviders(response.results.kz.ads),
      ),
      WatchProviders(
        isoCode: 'KP',
        nameCountry: Countries.isoToFlag('KP'),
        streaming: getProviders(response.results.kp.flatrate),
        rent: getProviders(response.results.kp.rent),
        buy: getProviders(response.results.kp.buy),
        ads: getProviders(response.results.kp.ads),
      ),
      WatchProviders(
        isoCode: 'KG',
        nameCountry: Countries.isoToFlag('KG'),
        streaming: getProviders(response.results.kg.flatrate),
        rent: getProviders(response.results.kg.rent),
        buy: getProviders(response.results.kg.buy),
        ads: getProviders(response.results.kg.ads),
      ),
      WatchProviders(
        isoCode: 'LA',
        nameCountry: Countries.isoToFlag('LA'),
        streaming: getProviders(response.results.la.flatrate),
        rent: getProviders(response.results.la.rent),
        buy: getProviders(response.results.la.buy),
        ads: getProviders(response.results.la.ads),
      ),
      WatchProviders(
        isoCode: 'LR',
        nameCountry: Countries.isoToFlag('LR'),
        streaming: getProviders(response.results.lr.flatrate),
        rent: getProviders(response.results.lr.rent),
        buy: getProviders(response.results.lr.buy),
        ads: getProviders(response.results.lr.ads),
      ),
      WatchProviders(
        isoCode: 'MH',
        nameCountry: Countries.isoToFlag('MH'),
        streaming: getProviders(response.results.mh.flatrate),
        rent: getProviders(response.results.mh.rent),
        buy: getProviders(response.results.mh.buy),
        ads: getProviders(response.results.mh.ads),
      ),
      WatchProviders(
        isoCode: 'MR',
        nameCountry: Countries.isoToFlag('MR'),
        streaming: getProviders(response.results.mr.flatrate),
        rent: getProviders(response.results.mr.rent),
        buy: getProviders(response.results.mr.buy),
        ads: getProviders(response.results.mr.ads),
      ),
      WatchProviders(
        isoCode: 'FM',
        nameCountry: Countries.isoToFlag('FM'),
        streaming: getProviders(response.results.fm.flatrate),
        rent: getProviders(response.results.fm.rent),
        buy: getProviders(response.results.fm.buy),
        ads: getProviders(response.results.fm.ads),
      ),
      WatchProviders(
        isoCode: 'NP',
        nameCountry: Countries.isoToFlag('NP'),
        streaming: getProviders(response.results.np.flatrate),
        rent: getProviders(response.results.np.rent),
        buy: getProviders(response.results.np.buy),
        ads: getProviders(response.results.np.ads),
      ),
      WatchProviders(
        isoCode: 'NE',
        nameCountry: Countries.isoToFlag('NE'),
        streaming: getProviders(response.results.ne.flatrate),
        rent: getProviders(response.results.ne.rent),
        buy: getProviders(response.results.ne.buy),
        ads: getProviders(response.results.ne.ads),
      ),
      WatchProviders(
        isoCode: 'NU',
        nameCountry: Countries.isoToFlag('NU'),
        streaming: getProviders(response.results.nu.flatrate),
        rent: getProviders(response.results.nu.rent),
        buy: getProviders(response.results.nu.buy),
        ads: getProviders(response.results.nu.ads),
      ),
      WatchProviders(
        isoCode: 'PW',
        nameCountry: Countries.isoToFlag('PW'),
        streaming: getProviders(response.results.pw.flatrate),
        rent: getProviders(response.results.pw.rent),
        buy: getProviders(response.results.pw.buy),
        ads: getProviders(response.results.pw.ads),
      ),
      WatchProviders(
        isoCode: 'KN',
        nameCountry: Countries.isoToFlag('KN'),
        streaming: getProviders(response.results.kn.flatrate),
        rent: getProviders(response.results.kn.rent),
        buy: getProviders(response.results.kn.buy),
        ads: getProviders(response.results.kn.ads),
      ),
      WatchProviders(
        isoCode: 'VC',
        nameCountry: Countries.isoToFlag('VC'),
        streaming: getProviders(response.results.vc.flatrate),
        rent: getProviders(response.results.vc.rent),
        buy: getProviders(response.results.vc.buy),
        ads: getProviders(response.results.vc.ads),
      ),
      WatchProviders(
        isoCode: 'SL',
        nameCountry: Countries.isoToFlag('SL'),
        streaming: getProviders(response.results.sl.flatrate),
        rent: getProviders(response.results.sl.rent),
        buy: getProviders(response.results.sl.buy),
        ads: getProviders(response.results.sl.ads),
      ),
      WatchProviders(
        isoCode: 'SB',
        nameCountry: Countries.isoToFlag('SB'),
        streaming: getProviders(response.results.sb.flatrate),
        rent: getProviders(response.results.sb.rent),
        buy: getProviders(response.results.sb.buy),
        ads: getProviders(response.results.sb.ads),
      ),
      WatchProviders(
        isoCode: 'SO',
        nameCountry: Countries.isoToFlag('SO'),
        streaming: getProviders(response.results.so.flatrate),
        rent: getProviders(response.results.so.rent),
        buy: getProviders(response.results.so.buy),
        ads: getProviders(response.results.so.ads),
      ),
      WatchProviders(
        isoCode: 'SS',
        nameCountry: Countries.isoToFlag('SS'),
        streaming: getProviders(response.results.ss.flatrate),
        rent: getProviders(response.results.ss.rent),
        buy: getProviders(response.results.ss.buy),
        ads: getProviders(response.results.ss.ads),
      ),
      WatchProviders(
        isoCode: 'SD',
        nameCountry: Countries.isoToFlag('SD'),
        streaming: getProviders(response.results.sd.flatrate),
        rent: getProviders(response.results.sd.rent),
        buy: getProviders(response.results.sd.buy),
        ads: getProviders(response.results.sd.ads),
      ),
      WatchProviders(
        isoCode: 'SR',
        nameCountry: Countries.isoToFlag('SR'),
        streaming: getProviders(response.results.sr.flatrate),
        rent: getProviders(response.results.sr.rent),
        buy: getProviders(response.results.sr.buy),
        ads: getProviders(response.results.sr.ads),
      ),
      WatchProviders(
        isoCode: 'TL',
        nameCountry: Countries.isoToFlag('TL'),
        streaming: getProviders(response.results.tl.flatrate),
        rent: getProviders(response.results.tl.rent),
        buy: getProviders(response.results.tl.buy),
        ads: getProviders(response.results.tl.ads),
      ),
      WatchProviders(
        isoCode: 'TK',
        nameCountry: Countries.isoToFlag('TK'),
        streaming: getProviders(response.results.tk.flatrate),
        rent: getProviders(response.results.tk.rent),
        buy: getProviders(response.results.tk.buy),
        ads: getProviders(response.results.tk.ads),
      ),
      WatchProviders(
        isoCode: 'TV',
        nameCountry: Countries.isoToFlag('TV'),
        streaming: getProviders(response.results.tv.flatrate),
        rent: getProviders(response.results.tv.rent),
        buy: getProviders(response.results.tv.buy),
        ads: getProviders(response.results.tv.ads),
      ),
      WatchProviders(
        isoCode: 'UZ',
        nameCountry: Countries.isoToFlag('UZ'),
        streaming: getProviders(response.results.uz.flatrate),
        rent: getProviders(response.results.uz.rent),
        buy: getProviders(response.results.uz.buy),
        ads: getProviders(response.results.uz.ads),
      ),
      WatchProviders(
        isoCode: 'VU',
        nameCountry: Countries.isoToFlag('VU'),
        streaming: getProviders(response.results.vu.flatrate),
        rent: getProviders(response.results.vu.rent),
        buy: getProviders(response.results.vu.buy),
        ads: getProviders(response.results.vu.ads),
      ),
      WatchProviders(
        isoCode: 'EH',
        nameCountry: Countries.isoToFlag('EH'),
        streaming: getProviders(response.results.eh.flatrate),
        rent: getProviders(response.results.eh.rent),
        buy: getProviders(response.results.eh.buy),
        ads: getProviders(response.results.eh.ads),
      ),
    ];

    return watchProviders;
  }
}
